services:
  db:
    image: mysql:8.0
    ports:
      - "3307:3306" 
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env.prod
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  django-web:
    build: .
    container_name: django-docker
    depends_on:
      db:
        condition: service_healthy
        restart: true
    volumes:
      - ./static:/app/staticfiles
    env_file:
      - .env.prod

  frontend-proxy:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    depends_on:
      - django-web

volumes:
  db_data: